### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by Lin-dashuai** [charlesyou999648/MONA#2]
README does not describe how to start training/testing 2D or 3D data. 

Can you provide complete steps to run the files?

How should the ACDC and MMWHS datasets mentioned in the paper be preprocessed? Are there corresponding preprocessing files in the project?

**Comment by charlesyou999648** [comment]
Thank you for your interests! Here is the sample code for medical image processing: [https://github.com/charlesyou999648/MONA/blob/3c70567c91ecf90e5dbee1b81a5946de3359bc40/code/dataset/med_preprocessing.py](url).
